name: Build And Test

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: true

    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Yarn install
        run: yarn install

      - name: Run Hardhat tests
        run: yarn test
